export default {
  // Auth
  LOGIN_PENDING: 'LOGIN_PENDING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',

  // Realtime
  REALTIME_CONNECTING: 'REALTIME_CONNECTING',
  REALTIME_CONNECTED: 'REALTIME_CONNECTED',
  REALTIME_DISCONNECTED: 'REALTIME_DISCONNECTED',
  REALTIME_LOGOUT: 'REALTIME_LOGOUT',
  REALTIME_RECV_MSG: 'REALTIME_RECV_MSG',
  REALTIME_TASK_STATUS: 'REALTIME_TASK_STATUS',
  REALTIME_TASK_ENGINE_STATUS: 'REALTIME_TASK_ENGINE_STATUS',
  REALTIME_CRACKED_PASSWORDS: 'REALTIME_CRACKED_PASSWORD',

  // Worker Status
  WORKER_STATUS_GET: 'WORKER_STATUS_GET',
  WORKER_STATUS_REFRESHING: 'WORKER_STATUS_REFRESHING',
  WORKER_STATUS_RETRIEVED: 'WORKER_STATUS_RETRIEVED',
  WORKER_STATUS_FAILED: 'WORKER_STATUS_FAILED',

  // Task Related
  TASKS: 'TASKS',
  TASKS_RETRIEVED: 'TASKS_RETRIEVED',
  TASKS_FAILED: 'TASKS_FAILED',

  HASH_TYPES: 'HASH_TYPES',
  HASH_TYPES_RETRIEVED: 'HASH_TYPES_RETRIEVED',
  HASH_TYPES_FAILED: 'HASH_TYPES_FAILED',

  NOTIFY_REQUESTED: 'NOTIFY_REQUESTED',
  NOTIFY_GRANTED: 'NOTIFY_GRANTED',
  NOTIFY_SEND: 'NOTIFY_SEND',

  SET_LANGUAGE: 'SET_LANGUAGE'
}
