name: Build master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 12

    - name: Install dependencies
      run: yarn install

    - name: Build UI
      run: yarn build

    - name: Upload release package
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
